vrhelmet/boxapp/urls.py
from django.urls import path
from boxapp import views

app_name = 'boxapp'

urlpatterns = [
    #path('checkout/', views.OrderListView.as_view(), name='order'),
    path('basket_adding/', views.basket_adding, name='basket_adding'),
    #url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    path('checkout/', views.checkout, name='checkout'),
    path('thanks/', views.checkout, name='thanks'),
    ##path('contact/', views.contacts, name='contact'),



]

# urlpatterns = [
#     path(r'^$', views.cart_detail, name='cart_detail'),
#     path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
#     path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
# ]

vrhelmet/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView

app_name = 'usersapp'

urlpatterns = [
    path('login/',  views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),
]

vrhelmet/vrhelmet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from prodapp.api_views import CategoryViewSet, HelmetsViewSet


router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'helmets', HelmetsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('boxapp.urls', namespace='orders')),
    path('', include('prodapp.urls', namespace='prodapp')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path(r'api/v0/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vrhelmet/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class SiteUser(AbstractUser):
    first_name = models.CharField(max_length=48, blank=True, null=True, default=None, verbose_name='Ваше имя')
    #email = models.EmailField(unique=True)
    phone = models.CharField(max_length=48, blank=True, null=True, default=None, verbose_name='Ваш телефон')
    is_manager = models.BooleanField(default=False)

class Carusel(models.Model):
    image1 = models.ImageField(upload_to='carusel', null=True, blank=True)
    image2 = models.ImageField(upload_to='carusel', null=True, blank=True)
    image3 = models.ImageField(upload_to='carusel', null=True, blank=True)

vrhelmet/usersapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import SiteUser


class RegistrationForm(UserCreationForm):
    class Meta:
        model = SiteUser
        fields = ('username', 'phone', 'password1', 'password2')
        # help_texts = {
        #     'username': None,
        #     'phone': None,
        #     'password1': None,
        #     'password2': None
        # }

vrhelmet/usersapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic.base import ContextMixin

from .forms import RegistrationForm
from django.views.generic import CreateView, DetailView
from .models import SiteUser
from prodapp.models import Helmets, Category, Carusel, Message
from rest_framework.authtoken.models import Token

class DateContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        category = Category.objects.all()
        carus = Carusel.objects.get()
        context.update({'category': category, 'carus': carus})
        return context
# Create your views here.
class UserLoginView(LoginView, DateContextMixin):
    model = SiteUser
    template_name = 'usersapp/login.html'


class UserCreateView(CreateView, DateContextMixin):
    model = SiteUser
    template_name = 'usersapp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')

class ManagerCreateView(CreateView, DateContextMixin):
    model = SiteUser
    template_name = 'usersapp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')

class UserDetailView(DetailView):
    template_name = 'usersapp/profile.html'
    model = SiteUser


def update_token(request):
    user = request.user
    # если уже есть
    if user.auth_token:
        # обновить
        user.auth_token.delete()
        Token.objects.create(user=user)
    else:
        # создать
        Token.objects.create(user=user)
    return HttpResponseRedirect(reverse('users:profile', kwargs={'pk': user.pk}))


def update_token_ajax(request):
    user = request.user
    # если уже есть
    try:
        user.auth_token.delete()
        token = Token.objects.create(user=user)
    except:
        token = Token.objects.create(user=user)
    return JsonResponse({'key': token.key})

vrhelmet/usersapp/templates/usersapp/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Магазин - Войти
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
<!--<div class="col-lg-4 col-md-6 mb-4">-->
<form class="form-horizontal" method="post">{% csrf_token %}
    <div class="form-group">
        <div class="col-lg-9">
            {{ form|crispy }}

        </div>
    </div>

                           <!-- <div class="form-group">
                                <div class="col-lg-8">
                                    <label>Имя</label>
                                    <span class="form-error">{{ form.name.errors }}</span>
                                    <input type="text" name="{{ form.name.html_name }}" class="form-control"
                                        value="{{ request.POST.name }}"
                                    >
                                </div>
                            </div>

                         <div class="form-group">
                                <div class="col-lg-8">
                                     <label>Пароль</label>
                                    <input type="password" class="form-control" id="exampleInputPassword1">
                                </div>
                            </div>


    <!--<div class="form-group">
        <label for="exampleInputEmail1">Ваш email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Введите пароль</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    <div>-->

        <button type="submit" class="btn btn-primary">Войти</button>
</form>
</div>
</div>
</div>
{% endblock %}

vrhelmet/usersapp/templates/usersapp/profile.html
{% extends "base.html" %}

{% block title %}
Профиль
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-lg-4 col-md-6 mb-4">
    Профиль пользователя {{object.username}}
    <hr>
    Токен:
<span id="token">{% if object.auth_token %} {{object.auth_token}} {% else %} не создан {% endif %}</span>

    <!--<form action="{% url 'users:update_token' %}">
        <button type="submit" class="btn btn-primary">Refresh token</button>
    </form>-->
    <hr>
    <button type="button" id="ajax-btn" class="btn btn-info">Refresh token ajax</button>
</div>
</div>
</div>
{% endblock %}

vrhelmet/usersapp/templates/usersapp/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Магазин - Регистрация
{% endblock %}

{% block content %}
<div class="container">
<div class="row">

<form class="form-horizontal" method="post">{% csrf_token %}
    <div class="form-group">
        <div class="col-lg-9">
            {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
        </div>
    </div>
</form>
<style>
     #hint_id_username, #hint_id_phone, #hint_id_password1, #hint_id_password2  {
         display: none;
     }
</style>
</div>
</div>
</div>
{% endblock %}