vrhelmet/boxapp/urls.py
from django.urls import path
from boxapp import views

app_name = 'boxapp'

urlpatterns = [
    #path('checkout/', views.OrderListView.as_view(), name='order'),
    path('basket_adding/', views.basket_adding, name='basket_adding'),
    #url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    path('checkout/', views.checkout, name='checkout'),
    path('thanks/', views.checkout, name='thanks'),
    ##path('contact/', views.contacts, name='contact'),



]

# urlpatterns = [
#     path(r'^$', views.cart_detail, name='cart_detail'),
#     path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
#     path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
# ]

vrhelmet/prodapp/urls.py
from django.urls import path
from prodapp import views

app_name = 'prodapp'

urlpatterns = [
    path('', views.MainListView.as_view(), name='index'),
    #path('contact/', views.contacts, name='contact'),
    path('card/<int:pk>/', views.CardDetailView.as_view(), name='card'),   #CardDetailView.as_view()
    path('contactform/', views.ContactFormCreateView.as_view(), name='contactform'),
    path('helmets_category/<int:pk>/', views.StandaloneListView.as_view(), name='helmets_category'),
    #path('console/', views.console, name='console')


]

vrhelmet/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView

app_name = 'usersapp'

urlpatterns = [
    path('login/',  views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),
]

vrhelmet/vrhelmet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from prodapp.api_views import CategoryViewSet, HelmetsViewSet


router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'helmets', HelmetsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('boxapp.urls', namespace='orders')),
    path('', include('prodapp.urls', namespace='prodapp')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path(r'api/v0/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vrhelmet/templates/base.html
{% load static %}

<!DOCTYPE html>

<body lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css/' %}" rel="stylesheet">

</head>


<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <div class="top_h_left">
      <p class="top_h_left_p">
        <b>Магазин:</b> пн - вскр: 9:00-21:00
       </p>
      <p class="top_h_left_abtn">
        <a class="top_h_left_abtn_a phone" href="tel:+74991111111"> 8 (499) 111-11-11</a>
      </p>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'prodapp:index' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'prodapp:contactform' %}">Contactform</a>
        </li>
        {% if user.is_authenticated%}
        <li class="nav-item">
          Привет,  <a href="{% url 'users:profile' pk=user.pk %}"> {{user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
        </li>
        {% endif %}
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <div class="basket-container">
              <a href="{% url 'boxapp:checkout' %}">Корзина <span id="basket_total_amount"></span><span id="basket_total_nmb">
                   {% if products_total_nmb %}
                            ({{ products_total_nmb }})
                        {% else %}
                            (0)
                        {% endif %}
                    </span></a>
              <div class="basket-items hidden">
                <ul class="">
                  {% for product_in_basket in products_in_basket %}
                  <li>{{ product_in_basket.product.name }} {{ product_in_basket.nmb }} шт.
                    по {{ product_in_basket.price_per_item }} руб.
                    <a class="delete-item" href="" data-product_id="{{ product_in_basket.id }}">x</a>
                  </li>
                  {% endfor %}

                </ul>
                <li class="nav-item">
                    <div class="text-right">
                    <a href="javascript:{}" class="call_btn" data-toggle="modal" data-target="#modalBoxCall" >заказать звонок</a>
                    </div>
                </li>
              </div>
            </div>
          </li>
        </ul>

      </ul>
    </div>
  </div>
</nav>
<br>
<br>
<br>
<!-- Page Content -->
<div class="container">
{% block base-content %}

  <div class="row">
    <div class="col-lg-12">
    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        {% if carus.image1 and carus.image2 and carus.image3 %}
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active" style="width: 1440px">
            <img src="{{carus.image1.url}}" width="1100px" alt="First slide">
          </div>
          <div class="carousel-item" style="width: 1440px">
            <img src="{{carus.image2.url}}" width="1100px" alt="Second slide">
          </div>
          <div class="carousel-item" style="width: 1440px">
            <!--<img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide"> -->
            <img src="{{carus.image3.url}}" width="1100px" alt="Third slide">
          </div>
        </div>
        {% endif %}
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  <!--</div>
</div>
    <div class="container">
      <div class="row">-->

    <div class="col-lg-3">
      <h1 class="my-4">VR-Trends</h1>
      {% for item in category %}

      <li class="list-group-item">
        <a href="{% url 'prodapp:helmets_category' pk=item.pk %}">                <!--class="list-group-item" были кнопки -->
          {{ item.name }}
        </a>
      </li>
      {% endfor %}
    </div>
    <!-- /.col-lg-3 -->
   <!-- </div>
  </div>-->
      <div class="col-lg-9">

        {% endblock %}
         {% block content %}  {% endblock %}
      </div>
    </div>
   </div>
</body>

<footer class="py-5 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
    <!-- /.container -->
</footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/scripts.js' %}"></script>

</html>