vrhelmet/boxapp/urls.py
from django.urls import path
from boxapp import views

app_name = 'boxapp'

urlpatterns = [
    #path('checkout/', views.OrderListView.as_view(), name='order'),
    path('basket_adding/', views.basket_adding, name='basket_adding'),
    #url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    path('checkout/', views.checkout, name='checkout'),
    path('thanks/', views.checkout, name='thanks'),
    ##path('contact/', views.contacts, name='contact'),



]

# urlpatterns = [
#     path(r'^$', views.cart_detail, name='cart_detail'),
#     path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
#     path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
# ]

vrhelmet/prodapp/urls.py
from django.urls import path
from prodapp import views

app_name = 'prodapp'

urlpatterns = [
    path('', views.MainListView.as_view(), name='index'),
    #path('contact/', views.contacts, name='contact'),
    path('card/<int:pk>/', views.CardDetailView.as_view(), name='card'),   #CardDetailView.as_view()
    path('contactform/', views.ContactFormCreateView.as_view(), name='contactform'),
    path('helmets_category/<int:pk>/', views.StandaloneListView.as_view(), name='helmets_category'),
    #path('console/', views.console, name='console')


]

vrhelmet/vrhelmet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from prodapp.api_views import CategoryViewSet, HelmetsViewSet


router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'helmets', HelmetsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('boxapp.urls', namespace='orders')),
    path('', include('prodapp.urls', namespace='prodapp')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path(r'api/v0/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vrhelmet/prodapp/models.py
from django.utils import timezone
from django.db import models
from django.utils.functional import cached_property

from usersapp.models import SiteUser

class ActiveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)

class MainManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_main=True)

class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    is_active = models.BooleanField(default=False)

    class Meta:
        abstract = True

class Category(models.Model):       #этот механизм включает функцию orm, т.е.данные сохраняются в бд
    #создаем поля. из models выбираем тип, в скобках парамерты поля
    name = models.CharField(max_length=100, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name ='category'
        verbose_name_plural = 'categories'


class Helmets(IsActiveMixin):
    name = models.CharField(max_length=64, unique=True)
    #artikul = models.PositiveIntegerField(unique=True)
    text = models.CharField(max_length=84, default='Новое поколение игровых гарнитур')
    description = models.TextField(blank=True)
    #image = models.ImageField(upload_to='helmets/', null=True, blank=True)
    price = models.PositiveIntegerField(default=1)
    stock = models.CharField(max_length=16)   #срок поставки
    guarantee = models.CharField(max_length=16, blank=True)
    sale = models.CharField(max_length=3, default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    #created = models.DateTimeField(auto_now_add=True, auto_now=False, default=timezone.now)
    #updated = models.DateTimeField(auto_now_add=False, auto_now=True, default=timezone.now)

    def __str__(self):
        return "%s, %s, %s" % (self.price, self.name, self.category)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'


class ProductImages(IsActiveMixin):
    objects = models.Manager()
    active_objects = ActiveManager()
    main_objects = MainManager()
    product = models.ForeignKey(Helmets, blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='product_images')
    image = models.ImageField(upload_to='helmets/')
    #is_active = models.BooleanField(default=False)
    is_main = models.BooleanField(default=False)
    #created = models.DateTimeField(auto_now_add=True, auto_now=False, default=timezone.now)
    #updated = models.DateTimeField(auto_now_add=False, auto_now=True, default=timezone.now)

    def __str__(self):
        return "%s" % self.id

    # @cached_property
    # def get_product_pk(self, pk):
    #     pk = Helmets.objects.get(pk=pk)
    #     return pk

    class Meta:
        verbose_name = 'image'
        verbose_name_plural = 'images'


class Carusel(models.Model):
    image1 = models.ImageField(upload_to='carusel', null=True, blank=True)
    image2 = models.ImageField(upload_to='carusel', null=True, blank=True)
    image3 = models.ImageField(upload_to='carusel', null=True, blank=True)
    image4 = models.ImageField( upload_to='carusel', null=True, blank=True )

    class Meta:
        verbose_name = 'carusel_image'
        verbose_name_plural = 'carusel_images'


# Заявка со страницы contactform
class Message(models.Model):
    name = models.CharField(max_length=128)
    #tel = models.CharField(max_length=16)
    email = models.EmailField(max_length=100)
    text = models.CharField(max_length=300)
    #user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)

    def __str__(self):
        return "%s, %s" % (self.id, self.email)

    class Meta:
        verbose_name = 'message'
        verbose_name_plural = 'messages'

vrhelmet/prodapp/forms.py
from typing import Tuple

from django import forms
from .models import Helmets, Message


class Contacts(forms.Form):
    name = forms.CharField(label='Имя')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')


class ContactForm(forms.ModelForm):
    # name = forms.CharField(label='Имя',
    #                        widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    # email = forms.EmailField(label='Email',
    #                         widget=forms.TextInput(attrs={'placeholder': 'email', 'class': 'form-control'}))
    # tel = forms.CharField(label='Телефон',
    #                       widget=forms.TextInput(attrs={'placeholder': 'phone', 'class': 'form-control'}))
    # message = forms.CharField(label='Введите сообщение', widget=forms.TextInput(attrs={'placeholder': 'email', 'class': 'form-control'}))

    # Чекбоксы
    #tags = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple())


    class Meta:
        model = Message
        #fields = '__all__'
        #fields = ('name', 'tel', 'email', 'text')
        exclude = ['user', ]

vrhelmet/prodapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.contrib.auth.mixins import UserPassesTestMixin


from .models import Helmets, Category, Carusel, Message, ProductImages


# Create your views here.

# def main_view(request):      #request не импортируем, но передаем
#     helmets = Helmets.objects.all()                   #будет запрос к БД
#     category = Category.objects.all()
#     carus = Carusel.objects.get()
#     #print(type(carus))
#     return render(request, 'prodapp/index.html', context={'category': category, 'helmets': helmets, 'carus': carus})    #request - чтобы данные запроса попали в шаблон

class DateContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        category = Category.objects.all()
        carus = Carusel.objects.first()
        context.update({'category': category, 'carus': carus})
        return context


class MainListView(ListView, DateContextMixin):
    model = ProductImages
    template_name = 'prodapp/index.html'
    paginate_by = 6


    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        #pk = ProductImages.get_product_pk
        return ProductImages.active_objects.select_related('product').filter(is_main=True, product__is_active=True)


#вариант написания вью для главной
# def index(request):
#     products_images = ProductImages.objects.filter(is_active=True, is_main=True, product__is_active=True)
#     products_images_phones = products_images.filter(product__category__id=1)
#     products_images_laptops = products_images.filter(product__category__id=2)
#     return render(request, 'prodapp/index.html', locals())

# def contacts(request):
#     return render(request, 'prodapp/contact.html')

# def contactform(request):
#     if request.method == 'POST':
#         contactform = ContactForm(request.POST)
#         if contactform.is_valid():
#             # Получить данные из форы
#             name = contactform.cleaned_data['name']
#             message = contactform.cleaned_data['message']
#             email = contactform.cleaned_data['email']
#
#             send_mail(
#                 'Contact message',
#                 f'Ваше сообщение {message} принято',
#                 'from@example.com',
#                 [email],
#                 fail_silently=True,
#             )
#
#             return HttpResponseRedirect(reverse('prodapp:index'))
#         else:
#             return render(request, 'prodapp/contactform.html', context={'contactform': contactform})
#     else:
#         contactform = ContactForm()
#         return render(request, 'prodapp/contactform.html', context={'contactform': contactform})

# форма контактов на странице контактов
class ContactFormCreateView(CreateView, DateContextMixin):
    fields = '__all__'
    model = Message
    success_url = reverse_lazy('prodapp:index')
    template_name = 'prodapp/contactform.html'

    def post(self, request, *args, **kwargs):
        """
        Пришел пост запрос
        """
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        # прописываем текущего пользователя
        # form.instance.user = self.request.user
        return super().form_valid(form)


# def card(request, id):
#     card = get_object_or_404(Helmets, id=id)
#     #card = Helmets.objects.get(id=id)
#     category = Category.objects.all()
#     return render(request, 'prodapp/card.html', context={'category': category, 'card': card})

# страничка отдельного товара
class CardDetailView(DetailView, DateContextMixin):
    model = Helmets
    template_name = 'prodapp/card.html'

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        """
        self.session = request.session
        session_key = self.session.session_key
        if not session_key:
            request.session.cycle_key()
        print(session_key)

        self.id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Helmets, id=self.id)

# выводим странички с товарами по категориям
class StandaloneListView(ListView, DateContextMixin):
    model = ProductImages
    template_name = 'prodapp/helmets_category.html'

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        """
        self.cat_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        return ProductImages.main_objects.select_related('product').filter(product__category__id=self.cat_id)

vrhelmet/prodapp/templates/prodapp/card.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{object.name}}
{% endblock %}

<!--{% block base-content %}{% endblock %}-->
{% block content %}
  <!-- Page Content -->

      <!-- /.col-lg-3 -->
<div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 mb-4">
        <!--<div class="card mt-4">-->
          <!-- {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %} вывести все картинки-->
          {% for image in object.product_images.all %}
          <!-- <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt=""> -->
          <img src="{{image.image.url}}" width="500px" class="img-responsive">

          <!--{% if object.sale %}
            <div class="sale-container">
                <span>{{ object.sale }}</span>
            </div>
          {% endif %}-->
          {% endfor %}
      </div>

      <div class="col-xs-6 col-md-6 mb-4">
          <p>
          </p>
            <h3 class="text-center">{{object.name}}</h3>
            <div class="">
                <p>
                    <h4 class="text-center">{{object.price}} руб./шт.</h4>
                </p>
            </div>
           <!-- <p class="card-text">{{object.description}}</p>-->
            <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
            4.0 stars

      <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active">
                  <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Описание</a>
                <!--<a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                  Описание
                </a>-->
              </li>
              <li role="presentation">
                  <a class="nav-link active" data-toggle="tab" href="#komplekt" role="tab">Комплектация</a>
                <!--<a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                  Доставка
                </a>-->
              </li>
              <li role="presentation"> <!--<a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a>-->
              <a class="nav-link active" data-toggle="tab" href="#charact" role="tab">Характеристики</a>
              </li>
              <!--<li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a>
                  <a class="nav-link active" data-toggle="tab" href="#settings" role="tab">Требования</a>
              </li>-->
            </ul>

            <!-- Tab panes -->
            <div class="tab-content product-description-tabs">
                <div class="tab-pane active" id="home" role="tabpanel">{{ object.description }}</div>
              <!--<div role="tabpanel" class="tab-pane active" id="description">
                {{ object.description }}
              </div>-->
                <div class="tab-pane" id="komplekt" role="tabpanel">Как мы делаем доставку</div>
              <!--<div role="tabpanel" class="tab-pane" id="delivery">
                <h3>Как мы делаем доставку</h3>
              </div>-->
              <div role="tabpanel" class="tab-pane" id="messages">...</div>
              <div role="tabpanel" class="tab-pane" id="settings">...</div>
            </div>
        <!-- /.card -->
            <div>
                   <!-- <form id="form_buying_product" class="form-inline">-->
                    <form id="form_buying_product" class="form-inline" action="{% url 'boxapp:basket_adding' %}">{% csrf_token %}
                        <div class="form-group">
                             <input type="number" class="form-control" name="number" id="number">
                        </div>
                            <div class="form-group">
                                <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                    data-product_id ="{{ object.id }}"
                                    data-name ="{{ object.name }}"
                                    data-price ="{{ object.price }}"
                                >
                                    Добавить в корзину
                                </button>
                            </div>
                    </form>
                </div>
        </div>
        <!-- /.card -->
    </div>
      <!-- /.col-lg-9 -->

  <!-- /.container -->
{% endblock %}
</div>

vrhelmet/prodapp/templates/prodapp/console.html
{% extends "base.html" %}

{% block title %}
  Магазин - Автономные VR-шлемы
{% endblock %}

{% block content %}

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">VR-Trends</h1>
        {% for item in category %}
        <div class="list-group">

          <a href="#" class="list-group-item">{{ item.name }}</a>

        </div>
        {% endfor %}

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">


        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>

          <div class="carousel-inner" role="listbox">
             <div class="carousel-item active">
              <img src="{{carus.image1.url}}" width="900px" alt="First slide">
            </div>
            <div class="carousel-item">
              <img src="{{carus.image1.url}}" width="900px" alt="Second slide">
            </div>
            <div class="carousel-item">
              <!--<img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide"> -->
            <img src="{{carus.image1.url}}" width="900px" alt="Third slide">
             </div>
          </div>

          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">
          {% for item in helmets %}

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">

              <a href="{% url 'prodapp:card' id=item.id %}"><img src="{{ item.image.url }}" width="250px"></a>   <!-- img class="card-img-top" "http://placehold.it/700x400" alt=""-->
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'prodapp:card' id=item.id %}">{{ item.name }}</a>
                </h4>
                <h5>{{ item.price }}</h5>
                <p class="card-text">{{ item.text }}</p>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
          {% endfor %}




        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

{% endblock %}

vrhelmet/prodapp/templates/prodapp/contactform.html
{% extends "base.html" %}

 <!-- Page Heading/Breadcrumbs -->
{% block title %}
    Контакты
{% endblock %}
  <!-- Page Content -->
  <!-- <div class="container">-->
<div class="container">
{% block base-content %}{% endblock %}

{% block content %}
  <!--<div>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active">Contact</li>
    </ol>
  </div>-->
    <!-- Content Row -->
  <div class="row">
      <!-- Map Column -->
      <div class="col-lg-8 mb-4">
        <!-- Embedded Google Map -->
        <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
      </div>
      <!-- Contact Details Column -->
      <div class="col-lg-4 mb-4">
        <h3>Contact Details</h3>
        <p>
          3481 Melrose Place
          <br>Beverly Hills, CA 90210
          <br>
        </p>
        <p>
          <abbr title="Phone">P</abbr>: (123) 456-7890
        </p>
        <p>
          <abbr title="Email">E</abbr>:
          <a href="mailto:name@example.com">name@example.com
          </a>
        </p>
        <p>
          <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM
        </p>
      </div>
  </div>
    <!-- /.row -->


 <div class="row">
      <!--<div class="col-lg-8 col-md-10 mx-auto"> -->
        <div class="col-lg-8 mb-4">  <!--было  <div class="col-lg-8 mb-4 "> чтобы поместить кнопку под форму подключила этот class, взяла у Л-->
        <!--<div class="col-lg-8 mb-10 ">-->
          <h3>Мы всегда на связи! </h3>
            <div>
              <form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}   <!--чтобы отправлять POST-запросы-->  <!--enctype="multipart/form-data"  может принимать файлы, в т.ч.картинки-->
                <div class="form-group">
                  <label for="exampleFormControlInput1">Ваше имя</label>
                  <input class="form-control" id="exampleFormControlInput1" placeholder="Имя">
                </div>
                <div class="form-group">
                  <label for="exampleFormControlInput1">Ваш email</label>
                  <input type="email" class="form-control" id="exampleFormControlInput2" placeholder="Email">
                </div>
                <div class="form-group">
                  <label for="exampleFormControlTextarea1">Сообщение</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <!-- {{ form.as_p }} -->
                <!--<div id="success"></div> было-->
          <!-- For success/fail messages -->
                <div>
                  <button type="submit" class="btn btn-primary" id="sendMessageButton">Отправить</button>
                </div>
              </form>
            </div>
        </div>
 </div>
    <!-- /.row -->
</div>
  <!-- /.container -->
{% endblock %}

vrhelmet/prodapp/templates/prodapp/helmets_category.html
{% extends "base.html" %}

{% block title %}
  Магазин - Главная страница
{% endblock %}

{% block content %}

  <!-- Page Content блок по категориям и карусель удалила в базовый шаблон-->


        <div class="row">
          {% for item in object_list %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{% url 'prodapp:card' pk=item.product.pk %}"><img src="{{ item.image.url }}" width="250px"></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'prodapp:card' pk=item.product.pk %}">{{ item.product.name }}</a>   <!-- id=item.id -->
                </h4>
                <h5>{{ item.product.price }} р.</h5>
                <p class="card-text">{{ item.product.text|truncatechars_html:70 }}</p>
                  <div class="add-to-card-btn">
                    <button type="submit" id="submit_btn" class="btn btn-success btn-buy">
                        <a href="{% url 'prodapp:card' pk=item.product.pk %}" style="color: white">
                                    Подробнее</a>

                    </button>
                  </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

{% endblock %}

vrhelmet/prodapp/templates/prodapp/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Магазин - Главная страница
{% endblock %}

{% block content %}

<div class="container">
        <div class="row">
          {% for item in object_list %}
            <div class="col-lg-4 col-md-3 mb-3">
            <div class="card h-100">
              <a href="{% url 'prodapp:card' pk=item.product.pk %}"><img src="{{ item.image.url }}" width="250px"></a>

              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'prodapp:card' pk=item.product.pk %}">{{ item.product.name }}</a>   <!-- id=item.id -->
                </h4>
                <h5>{{ item.product.price }}р.</h5>
                <p class="card-text">{{ item.product.text|truncatechars_html:70 }}</p>
                  <div class="add-to-card-btn">
                    <!--<button class="btn btn-success"--> <button type="submit" id="submit_btn" class="btn btn-success btn-buy">
                        <a href="{% url 'prodapp:card' pk=item.product.pk %}" style="color: white">
                                    Подробнее</a>

                    </button>
                  </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
            </div>
          {% endfor %}

         </div>
        <!-- /.row -->

      </div>


      <!-- /.col-lg-9 -->

      <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
        </span>
      </div>


    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

{% endblock %}